### PR TITLE
refactor build diagonal

### PR DESCRIPTION
**Pull request by nahid18**
the tests seem to work

### CODE REVIEW

**Comment by quattro** [comment]
Great! Let's keep this pull request open until we cover nearly all cases. For the compositional style operators (e.g., Tagged, Add, Mul, Composed), we can just make a recursive call. 

- [x] MatrixLinearOperator
- [ ] PyTreeLinearOperator
- [ ] JacobianLinearOperator
- [ ] FunctionLinearOperator
- [x] IdentityLinearOperator
- [x] DiagonalLinearOperator
- [x] TridiagonalLinearOperator
- [ ] TaggedLinearOperator
- [x] AddLinearOperator
- [x] MulLinearOperator
- [x] NegLinearOperator
- [x] DivLinearOperator
- [x] ComposedLinearOperator

**Review by nahid18 — COMMENTED** [review]
@quattro can you review the new push?

**Comment by quattro** [comment]
LGTM

**Comment by quattro** [comment]
Let's review and discuss before proceeding to the remaining operators.

**Pull request merged**
